name: "Continious Integration"

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    pull_request:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
    steps:
      - uses: action/checkout@v4.1.1
      - name: Set up JDK 21
        uses: action/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Test with Graadle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: --stacktrace --info test